# Generated by Django 3.1.3 on 2020-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.CharField(default='cZmYxLnuLs2Qsn8hKGIR9A', editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('viewing_permissions', models.CharField(choices=[('PU', 'public'), ('TO', 'tagged only'), ('FO', 'friends only'), ('PR', 'private')], max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
