# Generated by Django 3.1.3 on 2020-12-19 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20201219_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='memory',
            name='id',
            field=models.CharField(default='2qI0eog5o_hNLct4c5roLQ', editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='viewing_permissions',
            field=models.CharField(choices=[('PU', 'public'), ('TO', 'tagged only'), ('FO', 'friends only'), ('PR', 'private')], default='PR', max_length=2),
        ),
    ]
